kind: Deployment
apiVersion: apps/v1
metadata:
  name: a-system-app #deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-system-app
  template:
    metadata:
      labels:
        app: a-system-app
    spec:
      containers:
        - name: a-system-app #container name
          image: jp.icr.io/cti-roks-training/a-system-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: all-icr-io
---
kind: Service
apiVersion: v1
metadata:
  name: a-system-app #service name
spec:
  ports:
    - name: http-8080 #port name
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: a-system-app #deployment label
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: a-system-app #route name
spec:
  to:
    kind: Service
    name: a-system-app #service name
  tls:
    termination: edge
  port:
    targetPort: http-8080 #port name
