apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: a-system-pipeline-app1- #pipeline-run name
  namespace: a-system-cicd-demo #namespace
spec:
  params:
    - name: IMAGE_NAME
      value: 'jp.icr.io/cti-roks-training/a-system-app:latest'
    - name: GIT_REPO
      value: 'https://github.com/cti-roks/a-system-app.git'
    - name: GIT_REVISION
      value: main
  pipelineRef:
    name:  a-system-pipeline-app1
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: sample-pvc-1
